version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: API/Dockerfile.dev
    volumes:
      - .:/app
      - /app/API/bin
      - /app/API/obj
    ports:
      - "5000:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
